"""
LangGraph Pipeline State — ReasonSQL 2.0

Defines the typed state dictionary that flows through the LangGraph StateGraph.
Every node reads from and writes to this shared state object.

Why TypedDict over dataclass:
    - LangGraph requires TypedDict for state definitions
    - Supports `Annotated` for reducer functions (e.g., `add_messages`)
    - JSON-serializable by default (no custom __json__ needed)
    - Works with LangGraph's checkpointing system for state persistence
"""

from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langgraph.graph.message import add_messages


class PipelineState(TypedDict, total=False):
    """
    Shared state for the LangGraph NL→SQL pipeline.

    Fields are populated progressively as the pipeline executes.
    `total=False` means all fields are optional (nodes only set what they change).

    Lifecycle:
        schema_retrieval_node → reasoning_node → sql_generation_node
            → safety_validation_node → sql_execution_node
            → [self_correction_node] → response_synthesis_node
    """

    # -----------------------------------------------------------------
    # INPUT
    # -----------------------------------------------------------------
    user_query: str
    """Original natural language query from the user."""

    history: List[Dict[str, str]]
    """Conversation history for multi-turn context.
    Format: [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]
    """

    messages: Annotated[list, add_messages]
    """LangGraph message list (auto-accumulated via add_messages reducer)."""

    # -----------------------------------------------------------------
    # SCHEMA RETRIEVAL (schema_retrieval_node)
    # -----------------------------------------------------------------
    schema_context: str
    """Formatted schema string for the tables selected by RAG retrieval.
    Injected into LLM prompts as context.
    """

    retrieved_tables: List[str]
    """Table names selected by hybrid retrieval + cross-encoder reranking."""

    retrieval_method: str
    """How schema was retrieved: 'hybrid_rag' | 'full_schema'."""

    full_table_schemas: Dict[str, str]
    """All table schemas as text (needed for BM25/FAISS indexing)."""

    # -----------------------------------------------------------------
    # REASONING & PLANNING (reasoning_node)
    # -----------------------------------------------------------------
    intent: str
    """Query intent: 'DATA_QUERY' | 'META_QUERY' | 'AMBIGUOUS'."""

    intent_confidence: float
    """Intent classification confidence (0.0 - 1.0)."""

    resolved_query: str
    """Query after ambiguity resolution / assumption injection."""

    query_plan: str
    """High-level SQL query strategy from QueryPlanner."""

    assumptions: List[str]
    """Assumptions made by ClarificationAgent."""

    clarification_questions: List[str]
    """Questions generated when intent is AMBIGUOUS."""

    is_complex: bool
    """Whether the query requires multi-step SQL (subqueries, CTEs, etc.)."""

    # -----------------------------------------------------------------
    # SQL GENERATION (sql_generation_node)
    # -----------------------------------------------------------------
    generated_sql: str
    """Raw SQL generated by SQLGenerator agent."""

    # -----------------------------------------------------------------
    # SAFETY VALIDATION (safety_validation_node) — Deterministic
    # -----------------------------------------------------------------
    safety_approved: bool
    """Whether the SQL passed all safety checks."""

    safety_violations: List[str]
    """List of safety rule violations (if any)."""

    # -----------------------------------------------------------------
    # SQL EXECUTION (sql_execution_node) — Deterministic
    # -----------------------------------------------------------------
    execution_result: Optional[List[Dict[str, Any]]]
    """Raw query results as list of row dicts."""

    execution_error: str
    """Error message if SQL execution failed."""

    row_count: int
    """Number of rows returned by the query."""

    execution_time_ms: float
    """Query execution time in milliseconds."""

    # -----------------------------------------------------------------
    # SELF-CORRECTION (self_correction_node) — Conditional
    # -----------------------------------------------------------------
    retry_count: int
    """Number of self-correction attempts made."""

    max_retries: int
    """Maximum allowed self-correction attempts (from config)."""

    corrected_sql: str
    """SQL produced by SelfCorrectionAgent (replaces generated_sql on retry)."""

    correction_root_cause: str
    """Root cause analysis from SelfCorrectionAgent."""

    # -----------------------------------------------------------------
    # RESPONSE SYNTHESIS (response_synthesis_node)
    # -----------------------------------------------------------------
    final_answer: str
    """Human-readable answer synthesized from query results."""

    key_insights: List[str]
    """Key data insights extracted from the results."""

    # -----------------------------------------------------------------
    # PIPELINE METADATA
    # -----------------------------------------------------------------
    reasoning_trace: List[Dict[str, Any]]
    """Agent execution trace for debugging and UI display."""

    pipeline_error: str
    """Set when the pipeline aborts due to an unrecoverable error."""
